pipeline {
    agent any

    environment {
        IMAGE_NAME = "myapp"
        DOCKERHUB_USER = "sudarshan2244"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/sdarshandeshpande-395/ci-cd-jenkins-project.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $DOCKERHUB_USER/$IMAGE_NAME:latest app/'
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'USER',
                    passwordVariable: 'PASS'
                )]) {
                    sh '''
                    echo $PASS | docker login -u $USER --password-stdin
                    docker push $DOCKERHUB_USER/$IMAGE_NAME:latest
                    '''
                }
            }
        }

        stage('Deploy to DEV') {
            steps {
                sh 'kubectl apply -f k8s/dev/'
            }
        }

        stage('Approve QA') {
            steps {
                input "Deploy to QA?"
            }
        }

        stage('Deploy to QA') {
            steps {
                sh 'kubectl apply -f k8s/qa/'
            }
        }

        stage('Approve PROD') {
            steps {
                input "Deploy to PROD?"
            }
        }

        stage('Deploy to PROD') {
            steps {
                sh 'kubectl apply -f k8s/prod/'
            }
        }
    }
}
